f1_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'f1admin') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'f1analytics2025') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'f1_warehouse') }}"
      schema: analytics
      threads: 4

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: F1_DW
      warehouse: F1_WH
      schema: GOLD
      threads: 4
